export {default as Landing} from "./Landing/page"
export {default as Services} from "./Landing/Service Details/page"
export {default as Projects} from "./Projects/page"
export {default as Contact} from "./Contact/page"
export {default as Blogs} from "./Blogs/page"
export {default as Testinomials} from "./Testimonials/page"
export {default as CaseStudy} from "./CaseStudies/page"